### ISSUE TITLE
Infinite loop with exclusive access 

### ISSUE THREAD

**Issue by Zaner256** [HowProgrammingWorks/Pool#2]
## To reproduce
Pool from [9-exclusive.js](https://github.com/HowProgrammingWorks/Pool/commit/dcbed2a98a3e2f22b024ab525e890f2442383a6a#diff-5d14b54f1ada59fa921537274cde441f05d0d7bc5a317b4645f2327a4dfd2071) up to [b-timeout.js](https://github.com/HowProgrammingWorks/Pool/commit/e7723ea57182c37830cbff7b67117861579420ee#diff-c4d243ee878e5362afd823e1a09622bb3ba7e93fcd299b976e596310f37ec0d0)
```js
const pool = new Pool();
pool.add({ item: 1 });
pool.add({ item: 2 });
let x1 = pool.capture();
const x2 = pool.capture();
pool.release(x1);
x1 = pool.capture();
pool.release(x1);
const bottom = pool.capture(); //infinite loop in next(1)
```

**Comment by tshemsedinov** [comment]
Thanks, @Zaner256, fixed

**Comment by tshemsedinov** [comment]
Even shorter way to reproduce:
```js
pool.next();
pool.capture();
pool.next();
pool.capture();
```
@Zaner256
